version: "3.9"

services:
  server:
    image: localhost/server
    init: true
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "4"
    entrypoint: entrypoint.sh
    command: node server.js
    environment:
      - GROUP_ID
      - USER_ID
    extra_host:
      host.docker.internal:host-gateway
    networks:
      default:
        #ipv4_address: <>

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        #- subnet: <>